#!/bin/bash
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0/
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0/jre

cd $OPENSHIFT_DATA_DIR

export JAVACMD=$JAVA_HOME/bin/java
export M2_HOME=/usr/share/java/apache-maven-3.0.4


cd $OPENSHIFT_REPO_DIR/docuwiki

sed -i 's/@OPENSHIFT_MONGODB_DB_HOST@/'"$OPENSHIFT_MONGODB_DB_HOST"'/g' documentationWiki/src/main/resources/docuwiki.yml
sed -i 's/@OPENSHIFT_MONGODB_DB_PORT@/'"$OPENSHIFT_MONGODB_DB_PORT"'/g' documentationWiki/src/main/resources/docuwiki.yml

 /usr/share/java/apache-maven-3.0.4/bin/mvn -version

 /usr/share/java/apache-maven-3.0.4/bin/mvn clean package --settings $OPENSHIFT_REPO_DIR/.openshift/settings.xml > $OPENSHIFT_LOG_DIR/build.log