#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH
cd $OPENSHIFT_REPO_DIR/docuwiki/documentationWiki/target/
nohup java -jar documentationWiki-0.0.1-SNAPSHOT.jar server classes/docuwiki.yml > $OPENSHIFT_LOG_DIR/docuWiki.log
