server:
#  connector:
#    type: http
#    port: 8080
#    bindHost: 127.9.90.1
#  applicationContextPath: '/api'
#  rootPath: '/api'
#  applicationConnectors:
#    - type: http
#      bindHost: 127.9.90.1
#      port: 8080
  #type: simple
  applicationContextPath: /
  rootPath: '/api'
  adminContextPath: /admin

logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
    "org.forwoods.docuwiki":
      level: INFO
      additive: false
      appenders:
        - type: file
          currentLogFilename: docuwiki.log
          archivedLogFilenamePattern: docuwiki-%d.log.gz
          archivedFileCount: 5
    
  appenders:
    - type: console
  
mongoSecured : false
mongoUsername : docuWikiUser
mongoDatabase : docuWiki
mongoHost : localhost

xmlFileLocation: ${XML_FILE_LOC}/generated
squadXMLFileLocation: ${XML_FILE_LOC}/downloaded/squadXML.zip

squadXMLFileSource: https://kerbalspaceprogram.com/api/xml.zip

sundial:
  thread-pool-size: 1
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  annotated-jobs-package-name: org.forwoods.docuwiki.documentationWiki.jobs